### PR TITLE
Pluck functions and tests

### PR DESCRIPTION
**Pull request by slavaGanzin**

### CODE REVIEW

**Comment by Rafi993** [comment]
@slavaGanzin it would be awesome if each function repo has benchmarks created. The curry function seems to be the bottleneck and improving it to will help.

**Comment by slavaGanzin** [comment]
@Rafi993 
1. I don't found any benchmarks in this repo. I'm not familiar with benchmarking in python, so it's up to you. I will write benchmark for pluck if you will create some framework for this.

2. I think critical parts (like curry) can be rewriten with a touch of Cython. 

3. Whole library can be rewriten with ease to Cython.

4. You should use toolz: https://github.com/pytoolz/toolz ~ Cython port of itertools/functools

5. Ramda.js don't use their own functions in function realization for speedup. For example: https://github.com/ramda/ramda/blob/master/source/all.js do use `while` and not `map`

6. Maybe you want to publish this fork on https://pypi.org as "ramda" and separate this repo from jackfirth one? Because as I understand he abandon development.

**Comment by Rafi993** [comment]
Thanks for the info @slavaGanzin  yes functions in this library does not have benchmarks yet. I will look into it and sure this needs to be published in pypi.org. And as you said some functions that could be optimised by writing imperative code inside and some cases replacing by cython functions.

**Comment by Rafi993** [comment]
Actually thinking about it is better if we had a proper roadmap for this project to prevent it from getting stagnant. And publishing in pip is also a priority.

**Comment by slavaGanzin** [comment]
let's start with separating from jackfirth. At least we will have the "issues" tab

**Comment by Rafi993** [comment]
@slavaGanzin did you publish library in pip?

**Comment by slavaGanzin** [comment]
@Rafi993 
Yes. Here is a link: https://pypi.org/project/ramda/

And I moved development to: https://github.com/slavaGanzin/ramda.py

**Pull request merged**
