### PR TITLE
fix pycodestyle issues

### PR DESCRIPTION
**Pull request by slavaGanzin**
I use this hook. You may try to use it too:

cat .git/hooks/pre-push
```sh
#!/usr/bin/env sh

nosetests
pycodestyle
```

Additionally, I ask you to setup:
- https://coveralls.io/github/Rafi993/pyramda2?branch=master
- https://travis-ci.org/Rafi993/pyramda2

### CODE REVIEW

**Comment by Rafi993** [comment]
@slavaGanzin  since I am not active in maintaining this repo I am considering transfering its ownership to you. I have decided to move away from python to clojure.

**Comment by slavaGanzin** [comment]
@Rafi993 Deal. Transfer it to me

**Comment by Rafi993** [comment]
Awesome. Even though I will not be able to contribute to this project that much I will give pull requests if any

**Comment by slavaGanzin** [comment]
@Rafi993 Thanks, Rafi. Wish you easy transfer to clojure

**Pull request merged**
